version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - id: dockerbeam
    builder: rust
    binary: dockerbeam
    tool: "cross"
    flags:
      - --release
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      - i686-pc-windows-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin

archives:
  - id: main-archive
    builds:
      - rust-build
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: main
    package_name: dockerbeam
    maintainer: "ceo@cryptodarth.com"
    vendor: "cryptodarth"
    homepage: "https://www.dockerbeam.com"
    description: |-
      A P2P Docker image sharing tool
    license: "MIT"
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux



release:
  github:
    owner: DockerBeam
    name: DockerBeam
  draft: false
  prerelease: false
